# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Specify the version of the pre-commit-hooks repo
    hooks:
      - id: trailing-whitespace     # Removes trailing whitespace
      - id: end-of-file-fixer       # Ensures a newline at the end of files
      - id: check-merge-conflict    # Prevents committing unresolved merge conflicts

  - repo: https://github.com/psf/black
    rev: 23.9.1  # Version of the black formatter for Python
    hooks:
      - id: black                   # Formats Python files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.0  # Version of clang-format
    hooks:
      - id: clang-format            # Formats C/C++ files

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.5.0  # Version of eslint for JavaScript
    hooks:
      - id: eslint                  # Lints JavaScript files
