CONVEYOR_BELT: include/button.h File Reference
button.h File Reference
Button control and debounce handling for STM32.
#include "libopencm3/cm3/nvic.h"
#include "libopencm3/stm32/exti.h"
#include "libopencm3/stm32/gpio.h"
#include "libopencm3/stm32/rcc.h"
Macros
#define STOP_BUTTON_PORT GPIOB
GPIO port for the STOP button.
#define STOP_BUTTON_PIN GPIO10
GPIO pin for the STOP button.
#define CONTROL_BUTTON_PORT GPIOB
GPIO port for the CONTROL button.
#define CONTROL_BUTTON_PIN GPIO11
GPIO pin for the CONTROL button.
#define DEBOUNCE_DELAY 200
Debounce delay in milliseconds.
Functions
void button_init (void)
Initializes the buttons on specific GPIO pins with EXTI.
uint8_t button_get_stop_flag (void)
Retrieves the current stop flag state.
uint8_t button_get_object_flag (void)
Retrieves the current object flag state.
void button_set_object_flag (uint8_t boolean)
Sets the state of the object flag.
Detailed Description
Button control and debounce handling for STM32.
This file provides functions and definitions for initializing buttons on GPIO ports, reading button states, and managing debounce for reliable button presses. It includes configurations for a STOP button and a CONTROL button, each connected to specific pins on GPIOB. The debounce function helps to eliminate noise from mechanical button presses, ensuring reliable detection of button states.
Definition in file button.h.
Macro Definition Documentation
CONTROL_BUTTON_PIN
#define CONTROL_BUTTON_PIN GPIO11
GPIO pin for the CONTROL button.
Definition at line 35 of file button.h.
Referenced by button_init().
CONTROL_BUTTON_PORT
#define CONTROL_BUTTON_PORT GPIOB
GPIO port for the CONTROL button.
Definition at line 30 of file button.h.
Referenced by button_init().
DEBOUNCE_DELAY
#define DEBOUNCE_DELAY 200
Debounce delay in milliseconds.
Defines the delay duration for debounce logic to filter out noise from mechanical button presses.
Definition at line 43 of file button.h.
STOP_BUTTON_PIN
#define STOP_BUTTON_PIN GPIO10
GPIO pin for the STOP button.
Definition at line 25 of file button.h.
Referenced by button_init().
STOP_BUTTON_PORT
#define STOP_BUTTON_PORT GPIOB
GPIO port for the STOP button.
Definition at line 20 of file button.h.
Referenced by button_init().
Function Documentation
button_get_object_flag()
uint8_t button_get_object_flag (void)
Retrieves the current object flag state.
This function returns the status of the object flag, which indicates whether the CONTROL button has triggered an object detection event.
Returns
The state of the object flag (0 or 1).
Definition at line 66 of file button.c.
References button_get_object_flag().
Referenced by button_get_object_flag().
button_get_stop_flag()
uint8_t button_get_stop_flag (void)
Retrieves the current stop flag state.
This function returns the status of the stop flag, which indicates whether the STOP button has been pressed.
Returns
The state of the stop flag (0 or 1).
Definition at line 61 of file button.c.
References button_get_stop_flag().
Referenced by button_get_stop_flag().
button_init()
void button_init (void)
Initializes the buttons on specific GPIO pins with EXTI.
This function sets up the GPIO pins for the STOP and CONTROL buttons as inputs with pull-up resistors and enables external interrupt requests on both pins with specified edge triggers.
< Enable clock for Alternate Function I/O.
< Enable clock for GPIOB.
< Set EXTI15_10 interrupt priority to highest (0).
< Enable EXTI15_10 interrupt in NVIC.
< Select GPIO port for EXTI10 (PB10).
< Set EXTI10 trigger to falling edge.
< Select GPIO port for EXTI11 (PB11).
< Set EXTI11 trigger to rising edge.
< Enable interrupt request for EXTI10.
< Enable interrupt request for EXTI11.
Definition at line 9 of file button.c.
References button_init(), CONTROL_BUTTON_PIN, CONTROL_BUTTON_PORT, STOP_BUTTON_PIN, and STOP_BUTTON_PORT.
Referenced by button_init().
button_set_object_flag()
void button_set_object_flag (uint8_t boolean)
Sets the state of the object flag.
This function allows setting the object flag to a specified boolean value, typically used to reset the flag after handling an object detection event.
Parameters
boolean The new state to set for the object flag (0 or 1).
Definition at line 71 of file button.c.
References button_set_object_flag().
Referenced by button_set_object_flag(), and display_measure_info().