CONVEYOR_BELT: include/hc_sr04.h File Reference
hc_sr04.h File Reference
Ultrasonic sensor HC-SR04 driver for STM32 using libopencm3.
#include "libopencm3/cm3/nvic.h"
#include "libopencm3/stm32/gpio.h"
#include "libopencm3/stm32/rcc.h"
#include "libopencm3/stm32/timer.h"
Macros
#define TRIG_PIN GPIO8
Trigger pin for the HC-SR04 ultrasonic sensor.
#define ECHO_PIN GPIO9
Echo pin for the HC-SR04 ultrasonic sensor.
#define HCSR04_PORT GPIOB
GPIO port used for the HC-SR04 pins.
#define HCSR04_TIMER TIM4
Timer used to capture echo signal duration.
#define MHZ_DIVISOR 1000000
Divisor to convert MHz to Hz, used for timing calculations.
#define DELAY_10US 32
Delay in microseconds for the trigger pulse.
#define SOUND_SPEED_DIVISOR 116
Speed of sound in air, converted for sensor use.
#define MAX_CAP_DISTANCE 400.0
Maximum distance the HC-SR04 sensor can measure.
#define MIN_CAP_DISTANCE 2.0
Minimum distance the HC-SR04 sensor can measure.
Functions
void hcsr04_init (void)
Initializes the pins and timers needed for the HC-SR04.
void hcsr04_trigger (void)
Sends a 10 µs trigger pulse to the HC-SR04 sensor.
float hcsr04_get_distance (void)
Retrieves the distance measured by the HC-SR04 sensor in centimeters.
float saturation (void)
Applies saturation to the distance values to avoid out-of-range results.
Detailed Description
Ultrasonic sensor HC-SR04 driver for STM32 using libopencm3.
This file contains the functions necessary to initialize and retrieve the distance measured by the HC-SR04 ultrasonic sensor.
Definition in file hc_sr04.h.
Macro Definition Documentation
DELAY_10US
#define DELAY_10US 32
Delay in microseconds for the trigger pulse.
This value is used to generate a 10 µs pulse for the HC-SR04 sensor.
Definition at line 55 of file hc_sr04.h.
Referenced by hcsr04_trigger().
ECHO_PIN
#define ECHO_PIN GPIO9
Echo pin for the HC-SR04 ultrasonic sensor.
Receives the pulse back after reflecting from an object, allowing for the calculation of distance.
Definition at line 27 of file hc_sr04.h.
Referenced by hcsr04_init().
HCSR04_PORT
#define HCSR04_PORT GPIOB
GPIO port used for the HC-SR04 pins.
This port (GPIOB) contains both the trigger and echo pins for the sensor.
Definition at line 34 of file hc_sr04.h.
Referenced by hcsr04_init(), and hcsr04_trigger().
HCSR04_TIMER
#define HCSR04_TIMER TIM4
Timer used to capture echo signal duration.
TIM4 is used for timing the echo return to determine the distance.
Definition at line 41 of file hc_sr04.h.
Referenced by hcsr04_init().
MAX_CAP_DISTANCE
#define MAX_CAP_DISTANCE 400.0
Maximum distance the HC-SR04 sensor can measure.
This value is used to limit the distance readings to a reasonable range.
Definition at line 70 of file hc_sr04.h.
Referenced by saturation().
MHZ_DIVISOR
#define MHZ_DIVISOR 1000000
Divisor to convert MHz to Hz, used for timing calculations.
Used to set the timer's prescaler to achieve a 1 µs tick interval.
Definition at line 48 of file hc_sr04.h.
Referenced by hcsr04_init().
MIN_CAP_DISTANCE
#define MIN_CAP_DISTANCE 2.0
Minimum distance the HC-SR04 sensor can measure.
This value is used to limit the distance readings to a reasonable range.
Definition at line 77 of file hc_sr04.h.
Referenced by saturation().
SOUND_SPEED_DIVISOR
#define SOUND_SPEED_DIVISOR 116
Speed of sound in air, converted for sensor use.
Value derived from (343 m/s) divided by 2 (for round trip) and converted to cm/µs for accurate distance calculation in centimeters.
Definition at line 63 of file hc_sr04.h.
TRIG_PIN
#define TRIG_PIN GPIO8
Trigger pin for the HC-SR04 ultrasonic sensor.
Used to send a 10 µs pulse to start the distance measurement.
Definition at line 19 of file hc_sr04.h.
Referenced by hcsr04_init(), and hcsr04_trigger().
Function Documentation
hcsr04_get_distance()
float hcsr04_get_distance (void)
Retrieves the distance measured by the HC-SR04 sensor in centimeters.
This function measures the time taken for the echo pulse to return to the echo pin (ECHO_PIN) and calculates the distance in centimeters.
Returns
The measured distance in centimeters.
Start a new measurement by triggering the sensor
Wait until the measurement is complete
Return the measured distance with saturation applied
Definition at line 68 of file hc_sr04.c.
References hcsr04_get_distance(), hcsr04_trigger(), and saturation().
Referenced by hcsr04_get_distance(), and measure().
hcsr04_init()
void hcsr04_init (void)
Initializes the pins and timers needed for the HC-SR04.
This function configures the trigger pin (TRIG_PIN) as an output and the echo pin (ECHO_PIN) as an input, setting up the necessary timers to measure the duration of the echo pulse.
Flag to indicate completion of distance measurement
Enable clocks for GPIOB and TIM4
Configure TRIG_PIN as a 2 MHz output push-pull pin for triggering the sensor
Ensure TRIG_PIN is low initially
Configure ECHO_PIN as a floating input pin to receive the echo signal
– Configure TIM4 for input capture on channel 4, detecting both rising and falling edges –
Set up TIM4 Channel 4 to capture on the rising edge
Map TIM4 CH4 to GPIOB9
Rising edge for CH4
Enable input capture on CH4
Set up TIM4 Channel 3 to capture on the falling edge
Map TIM4 CH3 to GPIOB9
Falling edge for CH3
Enable input capture on CH3
Set the timer prescaler to create a 1 µs tick (based on APB1 frequency)
Start the timer
Enable interrupts for both capture channels
Enable NVIC interrupt for TIM4
Definition at line 7 of file hc_sr04.c.
References ECHO_PIN, hcsr04_init(), HCSR04_PORT, HCSR04_TIMER, MHZ_DIVISOR, and TRIG_PIN.
Referenced by hcsr04_init().
hcsr04_trigger()
void hcsr04_trigger (void)
Sends a 10 µs trigger pulse to the HC-SR04 sensor.
This function activates the trigger pin (TRIG_PIN) for 10 microseconds, generating a pulse to start the distance measurement on the HC-SR04.
Set TRIG_PIN high to start the pulse
Delay for approximately 10 µs
No-operation for precise timing
Set TRIG_PIN low to end the pulse
Definition at line 40 of file hc_sr04.c.
References DELAY_10US, HCSR04_PORT, hcsr04_trigger(), and TRIG_PIN.
Referenced by hcsr04_get_distance(), and hcsr04_trigger().
saturation()
float saturation (void)
Applies saturation to the distance values to avoid out-of-range results.
This function ensures that the distance values remain within a reasonable range, discarding any outlier or extreme values. Distances are constrained to a minimum and maximum allowable range for accurate readings.
Returns
The corrected distance value after applying saturation.
Cap distance at 400 cm if exceeded
Cap distance at 2 cm minimum
Return the measured distance if within range
Definition at line 81 of file hc_sr04.c.
References MAX_CAP_DISTANCE, MIN_CAP_DISTANCE, and saturation().
Referenced by hcsr04_get_distance(), and saturation().