CONVEYOR_BELT: include/lcd.h File Reference
lcd.h File Reference
LCD driver using STM32 microcontroller and I2C expander PCF8574.
#include "libopencm3/stm32/gpio.h"
#include "libopencm3/stm32/i2c.h"
#include "libopencm3/stm32/rcc.h"
Macros
#define PCF8574_ADDRESS 0x27
#define SDA_PIN GPIO7
#define SCL_PIN GPIO6
#define LCD_CLEARDISPLAY 0x01
#define LCD_RETURNHOME 0x02
#define LCD_ENTRYMODESET 0x04
#define LCD_DISPLAYCONTROL 0x08
#define LCD_FUNCTIONSET 0x20
#define LCD_SETDDRAMADDR 0x80
#define LCD_ENTRYLEFT 0x02
#define LCD_DISPLAYON 0x04
#define LCD_CURSOROFF 0x00
#define LCD_BLINKOFF 0x00
#define LCD_4BITMODE 0x00
#define LCD_2LINE 0x08
#define LCD_5x8DOTS 0x00
#define LCD_BACKLIGHT 0x08
#define LCD_NOBACKLIGHT 0x00
#define LCD_EN 0B00000100
#define LCD_RS 0B00000001
Functions
void lcd_init (void)
Initializes the LCD, pins, and I2C communication.
void lcd_pulse_enable (uint8_t data)
Sends a pulse to enable the LCD.
void lcd_send_nibble (uint8_t nibble, uint8_t mode)
Sends a nibble (4 bits) of data or command to the LCD.
void lcd_send_byte (uint8_t byte, uint8_t mode)
Sends a full byte of data or command to the LCD.
void lcd_print_char (char c)
Prints a single character on the LCD.
void lcd_print_string (const char *str)
Prints a string on the LCD.
void lcd_clear (void)
Clears the display data.
void lcd_set_cursor (uint8_t row, uint8_t col)
Sets the cursor to a specific position on the LCD.
void delay_ms (uint32_t ms)
Delays execution for a specified time in milliseconds.
Detailed Description
LCD driver using STM32 microcontroller and I2C expander PCF8574.
This file contains functions to initialize and control a 16x2 LCD via I2C protocol, using an STM32 microcontroller and a PCF8574 as an I2C expander.
Definition in file lcd.h.
Macro Definition Documentation
LCD_2LINE
#define LCD_2LINE 0x08
Flag to set 2-line display mode.
Definition at line 60 of file lcd.h.
Referenced by lcd_init().
LCD_4BITMODE
#define LCD_4BITMODE 0x00
Flag to set 4-bit data mode.
Definition at line 57 of file lcd.h.
Referenced by lcd_init().
LCD_5x8DOTS
#define LCD_5x8DOTS 0x00
Flag to set 5x8 character dot size.
Definition at line 63 of file lcd.h.
Referenced by lcd_init().
LCD_BACKLIGHT
#define LCD_BACKLIGHT 0x08
Flag to turn the LCD backlight on.
Definition at line 67 of file lcd.h.
Referenced by lcd_send_nibble().
LCD_BLINKOFF
#define LCD_BLINKOFF 0x00
Flag to disable cursor blinking.
Definition at line 53 of file lcd.h.
Referenced by lcd_init().
LCD_CLEARDISPLAY
#define LCD_CLEARDISPLAY 0x01
Command to clear the LCD screen.
Definition at line 24 of file lcd.h.
Referenced by lcd_clear(), and lcd_init().
LCD_CURSOROFF
#define LCD_CURSOROFF 0x00
Flag to turn the cursor off.
Definition at line 50 of file lcd.h.
Referenced by lcd_init().
LCD_DISPLAYCONTROL
#define LCD_DISPLAYCONTROL 0x08
Command to control the display settings.
Definition at line 33 of file lcd.h.
Referenced by lcd_init().
LCD_DISPLAYON
#define LCD_DISPLAYON 0x04
Flag to turn the display on.
Definition at line 47 of file lcd.h.
Referenced by lcd_init().
LCD_EN
#define LCD_EN 0B00000100
Enable bit.
Definition at line 73 of file lcd.h.
Referenced by lcd_pulse_enable().
LCD_ENTRYLEFT
#define LCD_ENTRYLEFT 0x02
Flag for left-to-right text entry mode.
Definition at line 43 of file lcd.h.
Referenced by lcd_init().
LCD_ENTRYMODESET
#define LCD_ENTRYMODESET 0x04
Command to set the LCD entry mode.
Definition at line 30 of file lcd.h.
Referenced by lcd_init().
LCD_FUNCTIONSET
#define LCD_FUNCTIONSET 0x20
Command to set LCD function parameters.
Definition at line 36 of file lcd.h.
Referenced by lcd_init().
LCD_NOBACKLIGHT
#define LCD_NOBACKLIGHT 0x00
Flag to turn the LCD backlight off.
Definition at line 70 of file lcd.h.
LCD_RETURNHOME
#define LCD_RETURNHOME 0x02
Command to return the cursor to the home position.
Definition at line 27 of file lcd.h.
LCD_RS
#define LCD_RS 0B00000001
Register select bit.
Definition at line 76 of file lcd.h.
Referenced by lcd_print_char().
LCD_SETDDRAMADDR
#define LCD_SETDDRAMADDR 0x80
Command to set DDRAM address.
Definition at line 39 of file lcd.h.
Referenced by lcd_set_cursor().
PCF8574_ADDRESS
#define PCF8574_ADDRESS 0x27
I2C address of the PCF8574.
Definition at line 14 of file lcd.h.
Referenced by lcd_pulse_enable().
SCL_PIN
#define SCL_PIN GPIO6
STM32 SCL pin.
Definition at line 20 of file lcd.h.
Referenced by lcd_init().
SDA_PIN
#define SDA_PIN GPIO7
STM32 SDA pin.
Definition at line 17 of file lcd.h.
Referenced by lcd_init().
Function Documentation
delay_ms()
void delay_ms (uint32_t ms)
Delays execution for a specified time in milliseconds.
This function introduces a delay by performing a software loop, which is useful for timing-sensitive operations on the LCD.
Parameters
ms Time to wait in milliseconds.
Create a delay in milliseconds
No-operation loop to create delay
Definition at line 108 of file lcd.c.
References delay_ms().
Referenced by delay_ms(), lcd_clear(), lcd_init(), lcd_pulse_enable(), and lcd_send_byte().
lcd_clear()
void lcd_clear (void)
Clears the display data.
This function clears any characters on the LCD screen and sets the cursor position to the home position.
Clear the LCD display
Send clear display command
Delay to allow LCD to process clear command
Definition at line 84 of file lcd.c.
References delay_ms(), lcd_clear(), LCD_CLEARDISPLAY, and lcd_send_byte().
Referenced by lcd_clear().
lcd_init()
void lcd_init (void)
Initializes the LCD, pins, and I2C communication.
This function configures the LCD for 4-bit mode, 2-line display, and enables the backlight if required. It also sets up the peripheral clock, I2C setup, and any other initial settings required for normal operation.
Initialize the LCD by setting up the I2C, configuring the LCD mode, and clearing the display
Enable GPIOB clock for I2C
Enable I2C1 clock
Set GPIOB SDA and SCL pins to I2C mode
Disable I2C1 to configure it
Set I2C to standard mode (100kHz)
Set I2C clock frequency to 36 MHz
Set rise time
Set I2C clock control register for 180kHz
Enable I2C1
Wait for LCD to power up
Send Function set command in 8-bit mode
Delay for LCD to process
Repeat 8-bit function set
Delay for LCD to process
Repeat once more
Delay for LCD to process
Switch to 4-bit mode
Delay for LCD to process
Configure LCD settings in 4-bit mode
4-bit, 2-line display
Display on, cursor off
Set entry mode: cursor moves left
Clear the display
Delay for display clear
Definition at line 32 of file lcd.c.
References delay_ms(), LCD_2LINE, LCD_4BITMODE, LCD_5x8DOTS, LCD_BLINKOFF, LCD_CLEARDISPLAY, LCD_CURSOROFF, LCD_DISPLAYCONTROL, LCD_DISPLAYON, LCD_ENTRYLEFT, LCD_ENTRYMODESET, LCD_FUNCTIONSET, lcd_init(), lcd_send_byte(), lcd_send_nibble(), SCL_PIN, and SDA_PIN.
Referenced by lcd_init().
lcd_print_char()
void lcd_print_char (char c)
Prints a single character on the LCD.
This function sends a single character to be displayed on the LCD at the current cursor position.
Parameters
c Character to print.
Send a single character to the LCD
Send character byte with RS (register select) high for data mode
Definition at line 69 of file lcd.c.
References lcd_print_char(), LCD_RS, and lcd_send_byte().
Referenced by lcd_print_char(), and lcd_print_string().
lcd_print_string()
void lcd_print_string (const char * str)
Prints a string on the LCD.
This function sends a null-terminated string to the LCD, printing it starting from the current cursor position.
Parameters
str Pointer to the null-terminated string to print.
Send a null-terminated string to the LCD
Loop through the string until null character
Print each character and move to the next
Definition at line 75 of file lcd.c.
References lcd_print_char(), and lcd_print_string().
Referenced by lcd_print_string().
lcd_pulse_enable()
void lcd_pulse_enable (uint8_t data)
Sends a pulse to enable the LCD.
This function sets the enable bit (EN) to latch the data or command currently being sent to the LCD.
Parameters
data Data to send along with the enable pulse.
Set the EN line high to latch the command, then set it low
Set the EN bit high
Send data with EN high to latch the command
Small delay for stability
Clear the EN bit
Send data with EN low to complete the pulse
Small delay to allow the LCD to process
Definition at line 4 of file lcd.c.
References delay_ms(), LCD_EN, lcd_pulse_enable(), and PCF8574_ADDRESS.
Referenced by lcd_pulse_enable(), and lcd_send_nibble().
lcd_send_byte()
void lcd_send_byte (uint8_t byte, uint8_t mode)
Sends a full byte of data or command to the LCD.
This function sends both nibbles of a byte to the LCD in 4-bit mode. It is used to send either data or commands, based on the mode parameter.
Parameters
byte 8-bit data to send.
mode Mode for the data (0 for command, 1 for data).
Split a byte into two nibbles and send each one to the LCD
Send the upper nibble
Send the lower nibble
Delay for LCD processing after sending the byte
Definition at line 24 of file lcd.c.
References delay_ms(), lcd_send_byte(), and lcd_send_nibble().
Referenced by lcd_clear(), lcd_init(), lcd_print_char(), lcd_send_byte(), and lcd_set_cursor().
lcd_send_nibble()
void lcd_send_nibble (uint8_t nibble, uint8_t mode)
Sends a nibble (4 bits) of data or command to the LCD.
This function sends the higher nibble of a byte in 4-bit mode to the LCD, typically used for initializing or sending data or commands.
Parameters
nibble 4-bit data to send.
mode Mode for the data (0 for command, 1 for data).
Prepare a nibble to be sent to the LCD and call pulse to latch it
Prepare the data: isolate the upper nibble, add mode and backlight
Send the nibble via pulse
Definition at line 16 of file lcd.c.
References LCD_BACKLIGHT, lcd_pulse_enable(), and lcd_send_nibble().
Referenced by lcd_init(), lcd_send_byte(), and lcd_send_nibble().
lcd_set_cursor()
void lcd_set_cursor (uint8_t row, uint8_t col)
Sets the cursor to a specific position on the LCD.
This function moves the cursor to a specified row and column on a 16x2 LCD display.
Parameters
row The row number (0 for the first row, 1 for the second row).
col The column number (0 to 15 for a 16x2 LCD).
Set the cursor to a specific row and column
Determine address for row 0
Determine address for row 1
Set DDRAM address to position cursor
Definition at line 91 of file lcd.c.
References lcd_send_byte(), lcd_set_cursor(), and LCD_SETDDRAMADDR.
Referenced by lcd_set_cursor().