CONVEYOR_BELT: include/motor_driver.h File Reference
motor_driver.h File Reference
Motor control driver using PWM for STM32 with libopencm3.
#include "libopencm3/stm32/gpio.h"
#include "libopencm3/stm32/rcc.h"
#include "libopencm3/stm32/timer.h"
Macros
#define MOTOR_PIN GPIO0
GPIO pin used for motor control.
#define MOTOR_PORT GPIOB
GPIO port for motor control.
#define MOTOR_PERIOD_MS 50
PWM period for motor control, specified in milliseconds.
#define MOTOR_DISABLED 0
Motor disabled state value.
#define MOTOR_ENABLED 1
Motor enabled state value.
#define MOTOR_TIMER TIM3
Timer used for generating PWM to control the motor.
#define MS_TO_SEC 1000
Conversion factor from milliseconds to seconds.
Functions
void motor_init (void)
Initializes the motor control GPIO and timer for PWM output.
void motor_set_power (uint8_t percentage)
Sets the motor power by adjusting the PWM duty cycle.
void motor_disable (void)
Disables the motor output by turning off the PWM signal.
void motor_enable (void)
Enables the motor output by turning on the PWM signal.
uint8_t motor_get_state (void)
Retrieves the current state of the motor.
Detailed Description
Motor control driver using PWM for STM32 with libopencm3.
This file contains the functions needed to initialize and control the power output of a motor using PWM on a specific GPIO pin. The driver allows setting up PWM, adjusting power levels by modifying the duty cycle, and enabling/disabling motor control.
Definition in file motor_driver.h.
Macro Definition Documentation
MOTOR_DISABLED
#define MOTOR_DISABLED 0
Motor disabled state value.
A constant representing the motor's disabled state.
Definition at line 40 of file motor_driver.h.
MOTOR_ENABLED
#define MOTOR_ENABLED 1
Motor enabled state value.
A constant representing the motor's enabled state.
Definition at line 47 of file motor_driver.h.
MOTOR_PERIOD_MS
#define MOTOR_PERIOD_MS 50
PWM period for motor control, specified in milliseconds.
Determines the frequency of the PWM signal, controlling the speed granularity.
Definition at line 33 of file motor_driver.h.
Referenced by motor_init(), and motor_set_power().
MOTOR_PIN
#define MOTOR_PIN GPIO0
GPIO pin used for motor control.
This pin outputs the PWM signal that controls the motor’s speed and state.
Definition at line 19 of file motor_driver.h.
Referenced by motor_init().
MOTOR_PORT
#define MOTOR_PORT GPIOB
GPIO port for motor control.
Defines the port associated with the motor control pin.
Definition at line 26 of file motor_driver.h.
Referenced by motor_init().
MOTOR_TIMER
#define MOTOR_TIMER TIM3
Timer used for generating PWM to control the motor.
Specifies the hardware timer associated with PWM generation.
Definition at line 54 of file motor_driver.h.
Referenced by motor_disable(), motor_enable(), motor_init(), and motor_set_power().
MS_TO_SEC
#define MS_TO_SEC 1000
Conversion factor from milliseconds to seconds.
Used to convert time periods in milliseconds to seconds.
Definition at line 61 of file motor_driver.h.
Referenced by motor_init(), and motor_set_power().
Function Documentation
motor_disable()
void motor_disable (void)
Disables the motor output by turning off the PWM signal.
This function stops the motor by disabling the PWM output on the configured pin, setting the motor to its MOTOR_DISABLED state.
< Set motor state to disabled
< Disable PWM output on TIM3 Channel 3
Definition at line 45 of file motor_driver.c.
References motor_disable(), and MOTOR_TIMER.
Referenced by motor_disable().
motor_enable()
void motor_enable (void)
Enables the motor output by turning on the PWM signal.
This function starts the motor by enabling the PWM output on the configured pin, setting the motor to its MOTOR_ENABLED state.
< Set motor state to enabled
< Enable PWM output on TIM3 Channel 3
Definition at line 51 of file motor_driver.c.
References motor_enable(), and MOTOR_TIMER.
Referenced by motor_enable(), and motor_init().
motor_get_state()
uint8_t motor_get_state (void)
Retrieves the current state of the motor.
Returns the motor state, indicating whether it is enabled (MOTOR_ENABLED) or disabled (MOTOR_DISABLED).
Returns
The current motor state (0 for disabled, 1 for enabled).
< Return the current motor state
Definition at line 57 of file motor_driver.c.
References motor_get_state().
Referenced by motor_get_state().
motor_init()
void motor_init (void)
Initializes the motor control GPIO and timer for PWM output.
This function sets up the GPIO pin and timer necessary to generate a PWM signal for motor control. The timer is configured with the appropriate period and output mode to ensure smooth and precise control of the motor speed.
< Enable clock for GPIOB
< Enable clock for TIM3
< Set MOTOR_PIN as 50 MHz alternate function push-pull output
< Configure TIMER in up-counting mode with auto-reload
< Enable preload for the timer
< Set prescaler to 72-1 for a 1 MHz tick frequency
< Set PWM period based on MOTOR_PERIOD_MS
< Disable output compare on TIM3 Channel 3
< Set output compare mode to PWM1 on TIM3 Channel 3
< Set duty cycle to 1%
< Enable motor output
< Start the timer counter
Definition at line 5 of file motor_driver.c.
References motor_enable(), motor_init(), MOTOR_PERIOD_MS, MOTOR_PIN, MOTOR_PORT, MOTOR_TIMER, and MS_TO_SEC.
Referenced by motor_init().
motor_set_power()
void motor_set_power (uint8_t percentage)
Sets the motor power by adjusting the PWM duty cycle.
This function adjusts the PWM duty cycle to control the motor power output. The power is set as a percentage, where 0% turns the motor off and 100% sets it to maximum power.
Parameters
percentage Power level as a percentage (0 to 100).
< Set power only if the motor is enabled
< Cap percentage at 100 to avoid exceeding maximum duty cycle
< Update duty cycle based on specified percentage
Definition at line 32 of file motor_driver.c.
References MOTOR_PERIOD_MS, motor_set_power(), MOTOR_TIMER, and MS_TO_SEC.
Referenced by motor_set_power(), and upt_pid().