CONVEYOR_BELT: include/pid.h File Reference
pid.h File Reference
Proportional-Integral-Derivative (PID) controller header file.
#include <stdint.h>
Data Structures
struct PID_Controller
Structure that holds the PID controller parameters and setpoint.
Macros
#define MAX_PID_OUTPUT 100
Maximum output value for the PID controller.
#define MIN_PID_OUTPUT 0
Minimum output value for the PID controller.
#define MAX_INTEGRAL_ERROR 30000.0
Maximum allowable accumulated error for the integral term to prevent windup.
Functions
void pid_init (PID_Controller *pid)
Initializes the PID controller with specified gains and desired reference.
uint8_t pid_update (float measured_value)
Updates the PID controller and calculates the control output.
void pid_setpoint (float setpoint)
Sets the desired setpoint for the PID controller.
Detailed Description
Proportional-Integral-Derivative (PID) controller header file.
This file defines the structure and functions necessary to initialize and control a PID controller. The PID controller computes an output based on the proportional, integral, and derivative terms derived from the error between a desired setpoint and a measured process variable.
Definition in file pid.h.
Macro Definition Documentation
MAX_INTEGRAL_ERROR
#define MAX_INTEGRAL_ERROR 30000.0
Maximum allowable accumulated error for the integral term to prevent windup.
Caps the accumulated error in the integral term to prevent excessive overshoot, a condition known as integral windup.
Definition at line 35 of file pid.h.
Referenced by pid_update().
MAX_PID_OUTPUT
#define MAX_PID_OUTPUT 100
Maximum output value for the PID controller.
Sets the upper bound for the controller’s output, typically representing 100% power or the maximum allowable effect of the controller on the system.
Definition at line 19 of file pid.h.
Referenced by pid_update().
MIN_PID_OUTPUT
#define MIN_PID_OUTPUT 0
Minimum output value for the PID controller.
Defines the lower bound for the controller's output, usually representing 0% power or the minimum effect of the controller.
Definition at line 27 of file pid.h.
Referenced by pid_update().
Function Documentation
pid_init()
void pid_init (PID_Controller * pid)
Initializes the PID controller with specified gains and desired reference.
This function sets up the PID controller structure with given proportional, integral, and derivative gains, as well as the initial setpoint for the control loop.
Parameters
pid Pointer to the PID controller structure.
Copy the control parameters into the local PID controller
Definition at line 7 of file pid.c.
References pid_init().
Referenced by pid_init().
pid_setpoint()
void pid_setpoint (float setpoint)
Sets the desired setpoint for the PID controller.
This function allows updating the setpoint of the PID controller, defining the target value that the system should aim to reach.
Parameters
setpoint The desired setpoint for the control loop.
Update the setpoint in the PID controller
Definition at line 53 of file pid.c.
References pid_setpoint(), and PID_Controller::setpoint.
Referenced by pid_setpoint(), and upt_pid().
pid_update()
uint8_t pid_update (float measured_value)
Updates the PID controller and calculates the control output.
This function computes the PID control output based on the current error between the setpoint and the measured value. It updates the integral and derivative terms, calculates the control action, and constrains it to the predefined limits.
Parameters
measured_value The current measured value of the process variable.
Returns
The control output, constrained between MIN_PID_OUTPUT and MAX_PID_OUTPUT.
Calculate the current error as the difference between setpoint and measured value
Update the integral term by adding the current error
Cap the integral to prevent windup
Limit the integral to a maximum threshold
Limit the integral to a minimum threshold
Calculate the derivative term as the difference from the previous error
Calculate the PID output based on the error, integral, and derivative terms
Constrain the output to ensure it stays within allowed limits
Cap output at the maximum limit
Cap output at the minimum limit
Save the current error to use in the next cycle for the derivative calculation
Return the constrained output as an 8-bit integer
Definition at line 12 of file pid.c.
References PID_Controller::kd, PID_Controller::ki, PID_Controller::kp, MAX_INTEGRAL_ERROR, MAX_PID_OUTPUT, MIN_PID_OUTPUT, pid_update(), and PID_Controller::setpoint.
Referenced by pid_update(), and upt_pid().