CONVEYOR_BELT: include/setpoint.h File Reference
setpoint.h File Reference
Potentiometer module for ADC with DMA on STM32.
#include <libopencm3/stm32/adc.h>
#include <libopencm3/stm32/dma.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>
Macros
#define N_DATA 10
Number of data samples to collect via DMA.
#define CONSTANT_TO_PERCENTAGE (24.42e-3) / N_DATA
Conversion constant to calculate potentiometer percentage value.
#define SAMPLE_TIME_CYCLES ADC_SMPR_SMP_239DOT5CYC
ADC sample time configuration.
#define POT_ADC ADC1
ADC used for potentiometer readings.
#define POT_ADC_CHANNEL ADC_CHANNEL9
ADC channel associated with the potentiometer input.
#define POT_DMA_CHANNEL DMA_CHANNEL1
DMA channel associated with the ADC.
#define POT_PORT GPIOB
GPIO port where the potentiometer pin is connected.
#define POT_PIN GPIO1
GPIO pin where the potentiometer is connected.
Functions
void pot_init (void)
Initializes the ADC and DMA for potentiometer readings.
float pot_get_value (void)
Retrieves the latest potentiometer value.
Detailed Description
Potentiometer module for ADC with DMA on STM32.
This module initializes an ADC to read values from a potentiometer using DMA. It includes functions to initialize the potentiometer ADC and retrieve the ADC value.
Definition in file setpoint.h.
Macro Definition Documentation
CONSTANT_TO_PERCENTAGE
#define CONSTANT_TO_PERCENTAGE (24.42e-3) / N_DATA
Conversion constant to calculate potentiometer percentage value.
Definition at line 18 of file setpoint.h.
Referenced by pot_get_value().
N_DATA
#define N_DATA 10
Number of data samples to collect via DMA.
Definition at line 15 of file setpoint.h.
Referenced by pot_get_value(), and pot_init().
POT_ADC
#define POT_ADC ADC1
ADC used for potentiometer readings.
Definition at line 24 of file setpoint.h.
POT_ADC_CHANNEL
#define POT_ADC_CHANNEL ADC_CHANNEL9
ADC channel associated with the potentiometer input.
Definition at line 27 of file setpoint.h.
Referenced by pot_init().
POT_DMA_CHANNEL
#define POT_DMA_CHANNEL DMA_CHANNEL1
DMA channel associated with the ADC.
Definition at line 30 of file setpoint.h.
Referenced by pot_init().
POT_PIN
#define POT_PIN GPIO1
GPIO pin where the potentiometer is connected.
Definition at line 36 of file setpoint.h.
Referenced by pot_init().
POT_PORT
#define POT_PORT GPIOB
GPIO port where the potentiometer pin is connected.
Definition at line 33 of file setpoint.h.
Referenced by pot_init().
SAMPLE_TIME_CYCLES
#define SAMPLE_TIME_CYCLES ADC_SMPR_SMP_239DOT5CYC
ADC sample time configuration.
Definition at line 21 of file setpoint.h.
Referenced by pot_init().
Function Documentation
pot_get_value()
float pot_get_value (void)
Retrieves the latest potentiometer value.
This function returns the current potentiometer reading as an ADC value. It should be called after pot_init has configured the ADC and DMA.
Returns
The ADC value corresponding to the potentiometer position (0-4095 for 12-bit resolution).
Get the potentiometer value by averaging the ADC buffer values
Accumulator for averaging buffer values
Sum up all values in the buffer
Return the average value, converted to a percentage
Definition at line 62 of file setpoint.c.
References CONSTANT_TO_PERCENTAGE, N_DATA, and pot_get_value().
Referenced by pot_get_value().
pot_init()
void pot_init (void)
Initializes the ADC and DMA for potentiometer readings.
This function configures the ADC and DMA to sample potentiometer values from the specified channel. It sets up GPIO, enables the required clocks, configures the ADC sample time, and initiates DMA for continuous data collection.
Buffer to store ADC readings for the potentiometer Initialize the potentiometer ADC and DMA setup
Enable peripheral clocks for GPIOB, ADC1, and DMA1
Configure the potentiometer GPIO pin as an analog input
Configure DMA1 Channel 1 for ADC requests
Reset DMA channel for fresh configuration
Set highest priority for the DMA channel
Set the DMA source address to ADC data register
Set the destination address to the buffer
Set the number of data elements to transfer
Configure memory data size as 16 bits
Configure peripheral data size as 16 bits
Enable circular mode for continuous data transfer
Enable memory increment mode to move through buffer
Configure DMA to read from the peripheral (ADC)
Enable the DMA channel
ADC setup: disable ADC to configure DMA settings
Turn off the ADC
Enable DMA mode in ADC
Disable end-of-conversion interrupt
Enable scan mode for multi-channel if needed
Disable internal temperature sensor channel
Enable continuous conversion mode
Set right alignment for ADC results
Set up the ADC channel sequence and sample time
Define the ADC channel for the potentiometer
Set ADC sequence to use only the specified channel
Set sample time for the channel
Power on the ADC and calibrate it
Turn on the ADC
Reset ADC calibration
Start ADC calibration
Wait for calibration to complete
Enable software trigger for conversion start
Start the ADC conversions
Definition at line 8 of file setpoint.c.
References N_DATA, POT_ADC_CHANNEL, POT_DMA_CHANNEL, pot_init(), POT_PIN, POT_PORT, and SAMPLE_TIME_CYCLES.
Referenced by pot_init().