CONVEYOR_BELT: include/speedometer.h File Reference
speedometer.h File Reference
Speedometer module for measuring rotational speed in RPM and rad/s.
#include <libopencm3/cm3/nvic.h>
#include <libopencm3/stm32/dma.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/timer.h>
Macros
#define PULSES_1TURN TIM_IC_PSC_8
#define SPEEDOMETER_PIN GPIO0
#define SPEEDOMETER_PORT GPIOA
#define TENMS_TIMER TIM1
#define ENCODER_TIMER TIM2
#define DMA_CH DMA_CHANNEL2
#define MS_PS 719
#define MS_INTERVAL 59999
#define CONSTANT_TO_RAD_S 1.309
#define CONSTANT_TO_RPM 12.5
Functions
void speedometer_init (void)
Initializes the speedometer module.
float speedometer_getRPM (void)
Gets the current speed in revolutions per minute (RPM).
float speedometer_getRAD_S (void)
Gets the current speed in radians per second (rad/s).
Detailed Description
Speedometer module for measuring rotational speed in RPM and rad/s.
This module provides functions to initialize a speedometer using an encoder connected to TIM2 as an external clock, and functions to retrieve the RPM and radian-per-second (rad/s) values. It configures the required timers and DMA to calculate rotational speed based on encoder pulses.
Definition in file speedometer.h.
Macro Definition Documentation
CONSTANT_TO_RAD_S
#define CONSTANT_TO_RAD_S 1.309
Constant to convert encoder counts to radian per second (rad/s).
Definition at line 43 of file speedometer.h.
Referenced by speedometer_getRAD_S().
CONSTANT_TO_RPM
#define CONSTANT_TO_RPM 12.5
Constant to convert encoder counts to revolutions per minute (RPM).
Definition at line 46 of file speedometer.h.
Referenced by speedometer_getRPM().
DMA_CH
#define DMA_CH DMA_CHANNEL2
DMA channel used for transferring data in speedometer operations.
Definition at line 34 of file speedometer.h.
Referenced by speedometer_init().
ENCODER_TIMER
#define ENCODER_TIMER TIM2
Timer configured as an encoder timer for measuring rotational speed.
Definition at line 31 of file speedometer.h.
Referenced by speedometer_init().
MS_INTERVAL
#define MS_INTERVAL 59999
Timer update interval for measuring rotation, set to 600 ms.
Definition at line 40 of file speedometer.h.
Referenced by speedometer_init().
MS_PS
#define MS_PS 719
Prescaler value for generating a 600 ms interval, used with TENMS_TIMER.
Definition at line 37 of file speedometer.h.
Referenced by speedometer_init().
PULSES_1TURN
#define PULSES_1TURN TIM_IC_PSC_8
High pulse count for one full rotation, defines encoder resolution.
Definition at line 19 of file speedometer.h.
SPEEDOMETER_PIN
#define SPEEDOMETER_PIN GPIO0
GPIO pin connected to the speedometer sensor.
Definition at line 22 of file speedometer.h.
Referenced by speedometer_init().
SPEEDOMETER_PORT
#define SPEEDOMETER_PORT GPIOA
GPIO port connected to the speedometer sensor.
Definition at line 25 of file speedometer.h.
Referenced by speedometer_init().
TENMS_TIMER
#define TENMS_TIMER TIM1
Timer used to measure intervals in milliseconds for speed calculation.
Definition at line 28 of file speedometer.h.
Referenced by speedometer_init().
Function Documentation
speedometer_getRAD_S()
float speedometer_getRAD_S (void)
Gets the current speed in radians per second (rad/s).
Uses the pulse count from the encoder to calculate speed in rad/s. This function provides a measure of rotational speed in radians per second, useful for precise control calculations.
Returns
The current speed in radians per second (rad/s).
Calculate and return the speed in radians per second based on encoder turns
Convert turns to rad/s
Definition at line 80 of file speedometer.c.
References CONSTANT_TO_RAD_S, and speedometer_getRAD_S().
Referenced by speedometer_getRAD_S().
speedometer_getRPM()
float speedometer_getRPM (void)
Gets the current speed in revolutions per minute (RPM).
Reads the pulse count from the encoder and calculates the speed in RPM based on the predefined constants. This function converts pulse data into a standard RPM measurement.
Returns
The current speed in RPM.
Calculate and return the speed in RPM based on encoder turns
Convert turns to RPM
Definition at line 72 of file speedometer.c.
References CONSTANT_TO_RPM, and speedometer_getRPM().
Referenced by speedometer_getRPM().
speedometer_init()
void speedometer_init (void)
Initializes the speedometer module.
Configures the necessary peripherals, including the encoder timer (TIM2), the control timer (TIM1), and the DMA channel used for data transfer. Sets up the speedometer GPIO as an input and enables external clocking on TIM2 to measure rotational speed based on encoder pulses.
Variable to store the number of encoder turns Initialize the speedometer by configuring timers, DMA, and GPIO
Enable clocks for DMA1, TIM2 (encoder timer), TIM1 (timer for measurements), and GPIOA
Configure speedometer GPIO pin as floating input
Configure TIM2 as an external clock source for the encoder
Set timer to external clock mode
Use an external trigger as the source
Trigger on rising edges
Set filter to reduce noise
Configure TIM1 (TENMS_TIMER) to generate periodic DMA requests
Set prescaler to adjust timer clock speed
Set timer period to 600ms
Set output compare value
Freeze output when counter reaches OC1 value
Enable DMA request on update events
Configure DMA1 Channel for reading TIM2 counter (encoder position)
Reset DMA channel to clear previous configuration
Set high priority for DMA transfers
Set DMA source to TIM2 counter register
Set DMA destination to turns variable
Transfer a single data item per request
Set peripheral data size to 16 bits
Set memory data size to 16 bits
Enable circular mode for continuous updates
Enable transfer complete interrupt to reset TIM2 counter after each DMA transfer
Enable interrupt on transfer completion
Enable NVIC interrupt for DMA channel 2
Start the DMA channel
Enable all counters to begin measurements
Start TIM2 (encoder timer)
Start TIM1 (measurement timer)
Definition at line 8 of file speedometer.c.
References DMA_CH, ENCODER_TIMER, MS_INTERVAL, MS_PS, speedometer_init(), SPEEDOMETER_PIN, SPEEDOMETER_PORT, and TENMS_TIMER.
Referenced by speedometer_init().