CONVEYOR_BELT: include/update.h File Reference
update.h File Reference
System update functions for speed and distance measurement.
#include "button.h"
#include "hc_sr04.h"
#include "lcd.h"
#include "motor_driver.h"
#include "pid.h"
#include "setpoint.h"
#include "speedometer.h"
#include "utils.h"
#include <libopencm3/cm3/systick.h>
Macros
#define TICKS_FOR_MS 72000
Number of ticks for a 1 ms interval at a system clock of 72 MHz.
#define PID_RATE 50
Sample time interval in milliseconds for PID updates.
#define DISPLAY_RATE 500
Sample time interval in milliseconds for updating the display.
#define MEASUREMENT_RATE 120
Sample time interval in milliseconds for object distance measurements.
#define N_MEASUREMENT 10
Number of samples taken for each distance measurement average.
#define MEASUREMENT_TRHS 10
Threshold distance for measurement evaluation in [cm].
#define MEASUREMENT_DISPLAY_TIME 3000
Duration in milliseconds to display the measurement result.
#define MAX_RPM 6500
Maximum revolutions per minute (RPM) for the motor.
Functions
void update_init (void)
Initializes the SysTick timer for system timing.
float get_measurement_prom (void)
Calculates the average of recorded measurements.
void display_speed (void)
Displays the current speed and target setpoint on the LCD.
void measure (void)
Records distance measurements from the ultrasonic sensor.
void display_measure_info (void)
Displays measurement information on the LCD.
void upt_pid (void)
Updates the PID controller for motor speed control.
Detailed Description
System update functions for speed and distance measurement.
This file contains functions for initializing the SysTick timer, handling periodic system updates (such as PID updates, LCD display updates, and distance measurements), and calculating the average distance measurement.
Definition in file update.h.
Macro Definition Documentation
DISPLAY_RATE
#define DISPLAY_RATE 500
Sample time interval in milliseconds for updating the display.
Definition at line 29 of file update.h.
MAX_RPM
#define MAX_RPM 6500
Maximum revolutions per minute (RPM) for the motor.
This constant defines the upper limit for the motor speed in RPM. It is used as a reference for setting the motor's speed range and calculating the setpoint.
Definition at line 49 of file update.h.
Referenced by upt_pid().
MEASUREMENT_DISPLAY_TIME
#define MEASUREMENT_DISPLAY_TIME 3000
Duration in milliseconds to display the measurement result.
Definition at line 41 of file update.h.
MEASUREMENT_RATE
#define MEASUREMENT_RATE 120
Sample time interval in milliseconds for object distance measurements.
Definition at line 32 of file update.h.
MEASUREMENT_TRHS
#define MEASUREMENT_TRHS 10
Threshold distance for measurement evaluation in [cm].
Definition at line 38 of file update.h.
Referenced by measure().
N_MEASUREMENT
#define N_MEASUREMENT 10
Number of samples taken for each distance measurement average.
Definition at line 35 of file update.h.
Referenced by get_measurement_prom(), and measure().
PID_RATE
#define PID_RATE 50
Sample time interval in milliseconds for PID updates.
Definition at line 26 of file update.h.
TICKS_FOR_MS
#define TICKS_FOR_MS 72000
Number of ticks for a 1 ms interval at a system clock of 72 MHz.
Definition at line 23 of file update.h.
Referenced by update_init().
Function Documentation
display_measure_info()
void display_measure_info (void)
Displays measurement information on the LCD.
Depending on whether a full set of measurements has been completed, this function will either display the measurement percentage or the average distance value. Used to provide feedback on object height or measurement completion.
< Display "Height:" label on the LCD.
< Display measurement value.
< Set flag to indicate measurement in display.
< Reset object flag.
< Reset for new measurements.
< Indicate that object measurement is in progress.
< Move cursor to the second row for setpoint display.
< Display measurement percentage.
Definition at line 145 of file update.c.
References button_set_object_flag(), display_measure_info(), float_to_string(), get_measurement_prom(), lcd_clear(), lcd_print_string(), and lcd_set_cursor().
Referenced by display_measure_info().
display_speed()
void display_speed (void)
Displays the current speed and target setpoint on the LCD.
Clears the LCD screen and shows the RPM of the motor along with the desired setpoint, updating the display with the latest values.
< Display "RPM:" label on the LCD.
< Display the current speed in RPM.
< Move cursor to the second row for setpoint display.
< Display "Target:" label for setpoint.
< Display the current setpoint in RPM.
Definition at line 102 of file update.c.
References display_speed(), float_to_string(), lcd_clear(), lcd_print_string(), and lcd_set_cursor().
Referenced by display_speed().
get_measurement_prom()
float get_measurement_prom (void)
Calculates the average of recorded measurements.
This function iterates through the measurement buffer and calculates the average distance. Used primarily for processing distance measurements from the sensor.
Returns
The average distance measurement.
Definition at line 92 of file update.c.
References get_measurement_prom(), and N_MEASUREMENT.
Referenced by display_measure_info(), get_measurement_prom(), and measure().
measure()
void measure (void)
Records distance measurements from the ultrasonic sensor.
This function performs distance measurements using the ultrasonic sensor, stores the results in a buffer, and determines if the measurement meets the pass/fail threshold.
< Store distance in the measurement buffer.
< Calculate average measurement.
< Set pass or fail flag based on threshold.
< Indicate measurement did not pass.
< Display the failed measurement.
< Stop the system and restart when object is not present.
Definition at line 112 of file update.c.
References float_to_string(), get_measurement_prom(), hcsr04_get_distance(), lcd_clear(), lcd_print_string(), measure(), MEASUREMENT_TRHS, and N_MEASUREMENT.
Referenced by measure().
update_init()
void update_init (void)
Initializes the SysTick timer for system timing.
Sets the reload value for generating an interrupt every millisecond, selects the AHB clock as the source, and enables both the counter and the interrupt.
< Set reload value for 1 ms.
< Use the AHB clock as the SysTick source.
< Enable the SysTick counter.
< Enable SysTick interrupt.
Definition at line 19 of file update.c.
References TICKS_FOR_MS, and update_init().
Referenced by update_init().
upt_pid()
void upt_pid (void)
Updates the PID controller for motor speed control.
Retrieves the current potentiometer value for the setpoint, obtains the current RPM from the speedometer, and adjusts motor power output based on the PID controller's calculations.
< Update setpoint based on potentiometer input.
< Retrieve the current speed in RPM.
< Update motor power based on PID output and current speed.
Definition at line 137 of file update.c.
References MAX_RPM, motor_set_power(), pid_setpoint(), pid_update(), pot_get_value(), speedometer_getRPM(), and upt_pid().
Referenced by upt_pid().