CONVEYOR_BELT: include/utils.h File Reference
utils.h File Reference
Provides a function to convert a floating-point number to a string.
#include <stdio.h>
Functions
char * float_to_string (float number)
Converts a floating-point number to a string.
Detailed Description
Provides a function to convert a floating-point number to a string.
This module defines a utility function for converting floating-point numbers to a string representation. Note that there is a known issue with handling certain multiples of 10, where precision limitations may cause unexpected formatting.
Definition in file utils.h.
Function Documentation
float_to_string()
char * float_to_string (float number)
Converts a floating-point number to a string.
This function takes a float as input and converts it to a string representation. Note that due to limitations in floating-point precision, some multiples of 10 (e.g., 10, 20, 30) may not be converted accurately.
Parameters
number The floating-point number to convert.
Returns
Pointer to a string representing the number.
Static buffer to hold the string (must be large enough to hold the output)
Extract the integer part of the float
Extract the decimal part (2 decimal places)
Handle the integer part
Index for placing characters in str
Handle case where integer part is 0
Add minus sign for negative numbers
Convert integer part to positive
Convert the integer part to a string without reversing
Temporary buffer to store the integer digits
Extract digits from right to left
Store each digit as a character
Remove the last digit from the number
Copy digits from temp to str in the correct order
Place each digit in the main string
Handle the decimal point only if necessary
Add decimal point
Handle the decimal part for negative values
Convert to positive
Convert and add the decimal part digits
Tens place
Units place
Null-terminate the string
Return the pointer to the static buffer
Definition at line 3 of file utils.c.
References float_to_string().
Referenced by display_measure_info(), display_speed(), float_to_string(), and measure().